version: '3'

services:
  service-balance:
    restart: unless-stopped
    image: nginx:1.12.0
    platform: 'linux/x86_64'
    volumes:
      - ./service-balance/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '4050:80'
    networks:
      - web-ui-network
      - worker-management-network

  web-ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./web-ui
    platform: 'linux/x86_64'
    networks:
      - web-ui-network
    environment:
      - WDS_SOCKET_PORT=4050
    volumes:
      - ./web-ui/src:/app/src

  worker-management:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker-management
    platform: 'linux/x86_64'
    volumes:
      - ./worker-management:/code
    networks:
      - worker-management-network
      - management-store-network
    command: python manage.py runserver 0.0.0.0:8000

  graph-nav-store:
    build:
      dockerfile: Dockerfile.dev
      context: ./graph-nav-store
    platform: 'linux/x86_64'
    ports:
      - '4051:1234'
    networks:
      - worker-management-network
    command: python /code/py-web-vue-master/examples/VTK/SimpleCone/RemoteViewLocalRendering/app.py --port 1234 --host 0.0.0.0 --debug

volumes:
  service-balance:
    driver: local
  worker-management:
    driver: local
  web-ui:
    driver: local

networks:
  web-ui-network:
    driver: "bridge"
  worker-management-network:
    driver: "bridge"
  management-store-network:
    external: true
    name: onthespot_management-store-network
