version: '3'

services:
  service-balance:
    restart: unless-stopped
    image: nginx:1.12.0
    volumes:
      - ./service-balance/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '4050:80'
    networks:
      - web-ui-network
      - worker-management-network

  web-ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./web-ui
    networks:
      - web-ui-network

  worker-management:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker-management
    volumes:
      - ./worker-management:/code
    networks:
      - worker-management-network
      - management-store-network
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  service-balance:
    driver: local
  worker-management:
    driver: local

networks:
  web-ui-network:
    driver: "bridge"
  worker-management-network:
    driver: "bridge"
  management-store-network:
    external: true
    name: onthespot_management-store-network
