version: '3'

services:
  management-store:
    build:
      dockerfile: Dockerfile.dev
      context: ./management-store
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: testcase
      MYSQL_USER: FinalBot
      MYSQL_PASSWORD: Trym3B30nc3
    volumes:
      - ./management-store-data:/var/lib/mysql
      - ./management-store:/scripts
    networks:
      - management-store-network

networks:
  management-store-network:
    driver: "bridge"