version: '3'

services:
  management-store:
    build:
      dockerfile: Dockerfile.dev
      context: ./management-store
    platform: 'linux/x86_64'
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: testcase
      MYSQL_USER: FinalBot
      MYSQL_PASSWORD: Trym3B30nc3
    volumes:
      - ./management-store-data:/var/lib/mysql
      - ./management-store:/scripts
    networks:
      - management-store-network

  graph-nav-store:
    build:
      dockerfile: Dockerfile.dev
      context: ./graph-nav-store
    platform: 'linux/x86_64'
    volumes:
      - ./graph-nav-store:/code
    networks:
      - graph-nav-store-network
    command: python manage.py runserver 0.0.0.0:8000

networks:
  management-store-network:
    driver: "bridge"
  graph-nav-store-network:
    driver: "bridge"